### PR TITLE
Show cursor same way in icon view and tree view

### PR DESCRIPTION
**Pull request by jeremypw**
Based on #1140 

IconView - No selection, focus on first item:
Screenshot from 2020-01-22 12 51 00

IconView - Two selected, focus on second item:
Screenshot from 2020-01-22 12 52 49

ListView - No selection, focus on first item:
Screenshot from 2020-01-22 12 55 43

ListView - Two selected, focus on second item:
Screenshot from 2020-01-22 12 54 21

### CODE REVIEW

**Comment by fabiozaramella** [comment]
Mmmh it seems to work but when compiling it complaint about:
`../src/TextRenderer.vala:126.18-126.23: warning: local variable `prelit' declared but never used`
`../src/TextRenderer.vala:127.18-127.25: warning: local variable `selected' declared but never used`
`../src/IconRenderer.vala:158.18-158.24: warning: local variable `focused' declared but never used`

Also this style for selected item looks really broken... 😕️

**Comment by jeremypw** [comment]
@fabiozaramella Yes, I was waiting for input from the design team before spending too much time on this.

**Comment by fabiozaramella** [comment]
> @fabiozaramella Yes, I was waiting for input from the design team before spending too much time on this.

Fine, I'm tagging the @elementary/ux team then.

**Comment by jeremypw** [comment]
Closing as this does not seem to have any traction.

**Pull request closed without merging**
