### PR TITLE
Fix cut and paste with Spanish Dvorak keyboard. (#257)

### LINKED ISSUE #257: Ctrl+C, Ctrl+V, etc do not work on internationalized layouts
Ctrl+C, Ctrl+V, and probably other keyboard shortcuts do not work on internationalized layouts.
For example, it works on English layout, but doesn't work if I switch to Spanish Dvorak layout.
This bug was reported and fixed on [Launchpad bug #1405315](https://bugs.launchpad.net/pantheon-files/+bug/1405315). It's happening again in Elementary OS Loki.

Files version: 0.3.5
Kernel version: 4.10.0-40-generic

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/52266707-ctrl-c-ctrl-v-etc-do-not-work-on-internationalized-layouts?utm_campaign=plugin&utm_content=tracker%2F65602118&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F65602118&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by jeremypw**
Fixes #257 

Should be tested with a range of internationalized keyboard layouts

### CODE REVIEW

**Comment by Djaler** [comment]
@tintou it works for me. But master works too :) So, maybe problem only in unusual layouts, like Dvorak.

**Comment by jeremypw** [comment]
Yes, the fix was for Dvorak and other unusual layouts - the Russian keyboard was previously fixed following a launchpad bug report :-)

**Comment by tetebueno** [comment]
Hi, I've tested this in a Juno environment using Spanish Dvorak layout. Works like a charm. Functionality lost in Loki is recovered with these changes.

Let me know if this is enough as a review to approve the change.

Cheers.

**Comment by jeremypw** [comment]
@tetebueno Thanks! That is very helpful. Hopefully the team will merge it now.

**Pull request merged**
