### PR TITLE
Regression: Fix dragging file items

### PR DESCRIPTION
**Pull request by jeremypw**
Dragging file items recently stopped working - this fixes that.

### CODE REVIEW

**Review by danirabbit — APPROVED** [review]
Fixes the issue! nice work

**Comment by jeremypw** [comment]
CI failing due to a change introduced by #2307 although it passed at the time??  Insufficient glib version.

**Comment by danirabbit** [comment]
Yeah something funny there, but not the fault of this branch so overridden

**Comment by jeremypw** [comment]
Is any fix required in Files? It will go away in elementary 8.

**Pull request merged**
