### PR TITLE
Double click option

### LINKED ISSUE #1960: Allow disabling single click to open on folder
### Problem

Single click on folder opens it.

`gsettings set io.elementary.files.preferences single-click false` does not work anymore. There seems to be no way of going around this while using elementary OS/files.

**Background**
Sometimes I need rename many folders one by one. This is simply too challenging with what current UX offers.

It is frustrating to click on a folder to rename, then go back, then rename it. Trying to click on the blue tick is not so productive when you need to be fast to get things done but also be pixel perfect.

### Proposal

Introduce a setting to disable single click to open folder.

### Prior Art (Optional)

_No response_

### PR DESCRIPTION
**Pull request by jeremypw**
Fixes #1960 

Providing this option only requires relatively trivial changes to the click handling code.  Most of the diff is providing the UX to change the option the remember it state.

For simplicity the option accompanies other similar settings toggles in the view context menu, although it would be perhaps better placed in an AppMenu.

It is not necessary to install the PR to test the UX and functionality but in that case the setting will not be persisted.

### CODE REVIEW

**Comment by ibrahimrahman** [comment]
Any possibility to have this at least reviewed before OS7?

**Review by JoseExposito — APPROVED** [review]
Thanks for this change @jeremypw, the code looks good, and after a quick test it works as expected.

There is a little conflict with `master` though.

I'm absolutely in favor of adding this option, but I know some people preferred to not include it. It'd be nice to have more feedback about it.

**Comment by jeremypw** [comment]
@JoseExposito Thanks for the review! What was the conflict with master you mentioned? Github is not showing anything.  I'll not merge this before more comment as it is likely to be controversial.

**Comment by JoseExposito** [comment]
@jeremypw I got a conflict rebasing on top of master, but it looks like it was on my end, GitHub didn't have any issues merging master into you branch.

> I'll not merge this before more comment as it is likely to be controversial.

Agrees. I truly think that it is great to provide this option, but it could be controversial.

**Comment by zeebok** [comment]
I think if it is an option, I see no issue with it being added. For me the vision of the project should be the defaults, not always the *only* way. Particularly something like this that can really mess with people's workflow.

**Pull request merged**
