### PR TITLE
Release 6.3.1

### PR DESCRIPTION
**Pull request by jeremypw**
- [x] Update version in meson
 - [x] Update appdata
 - [x] Merge bitesize PRs 
 - - [x] #2150
 - - [x] #2157

### CODE REVIEW

**Comment by jeremypw** [comment]
@danirabbit Just to clarify - does one need to update the screenshot locations for every release even if the screenshots are not new?  Or were they changed?

**Comment by danirabbit** [comment]
@jeremypw probably not? But I figure to be safe :sweat_smile:

**Review by danirabbit — APPROVED** [review]
Looks good! Nice release :rocket:

**Comment by jeremypw** [comment]
> @jeremypw probably not? But I figure to be safe sweat_smile

OK, I never used to but may AppCenter requires it now :shrug: .  I'll make a note to do it from now on.

**Comment by jeremypw** [comment]
@danirabbit Just another clarification; appdata should now include *all* issues fixed in the <issues> section, even technical or internal changes? We did not used to mention these in the <description> section.

**Comment by danirabbit** [comment]
@jeremypw Yeah the `<issues>` tag should include any github issues that were closed and the label there is supposed to match the title of the issue in GitHub, according to the spec. And the `description` tag should be a non-technical description of changes and can be basically whatever we want to say. So if you wanted to write release notes that were more personal or like a mini blog or whatever you could :) I've seen folks say they appreciate more descriptive release notes for iOS updates for example

**Comment by jeremypw** [comment]
@danirabbit Ah right, that's helpful.  Presumably you *could* edit the issue description in GitHub if were unacceptable in some way e.g. bad spelling, bad grammar or unintelligible although I guess that should have been done earlier ...  But basically you describe the problem not the fix.

**Comment by danirabbit** [comment]
Yeah exactly!

**Pull request merged**
