### PR TITLE
Do not stop search when unfocusing the window

### PR DESCRIPTION
**Pull request by donadigo**
This allows the user to freely unfocus the window and let Files search for a query instead of just stopping the search operation.

### CODE REVIEW

**Comment by donadigo** [comment]
After some more testing, this is ready to review.

**Comment by jeremypw** [comment]
A side effect of this change is that if another window is focussed during a search and that window overlays the main Files window then the search window remains on top, if already showing, or pops up over the other app when search completes with matches.  Clicking on a match under these conditions navigates Files as expected but does not focus the Files window, which remains hidden.

Is this the desired behaviour?   I can see that some notification of search completion is desirable, but if you click on a match I think Files should be focussed.

**Comment by jeremypw** [comment]
@donadigo :  Yes, please fix in this branch unless it requires large changes (I don't imagine it will).

**Comment by donadigo** [comment]
@jeremypw done.

**Comment by jeremypw** [comment]
Reverted by #481 due to unforeseen side-effects including possible crash.

Was the main reason for this to keep a lengthy search going while doing something else?  Maybe a different solution can be found.

**Comment by donadigo** [comment]
@jeremypw yes, that was the main reason I did this. Perhaps it's time to rethink search entirely?

**Comment by jeremypw** [comment]
Yes.  As mentioned in Slack maybe splitting it into separate widgets rather than having one multi-mode widget would be simpler.

**Pull request merged**
