### PR TITLE
[RegressionFix] Window: Propagate key events when view not having focus

### LINKED ISSUE #2392: Search resets after pressing /
### What Happened?

When I try to type a path into a search bar it gets reset every time I press `/`

### Steps to Reproduce

1. Open Files
2. Try to navigate using the search bar

### Expected Behavior

Being able to type a path into a search bar

### OS Version

Early Access

### Software Version

Latest release (I have run all updates)

### Log Output

_No response_

### Hardware Info

_No response_

### PR DESCRIPTION
**Pull request by jeremypw**
Fixes #2392

### CODE REVIEW

**Review by lenemter — COMMENTED** [review]
In this branch I have to press Ctrl + F to focus search bar and use it. In `main` it focuses automatically.

**Comment by jeremypw** [comment]
@lenemter Thanks for spotting that!  I think I have fixed it properly now.

**Comment by jeremypw** [comment]
With these changes needed to ensure that the active slot has keyboard focus else switching tabs between an unloadable view (cannot focus) and a loaded view (can focus) did not cause the view to become focussed so key events were not processed.

**Review by lenemter — APPROVED** [review]
Fixes the issue for me.

**Pull request merged**
