### PR TITLE
Add keyboard shortcuts to tooltips

### PR DESCRIPTION
**Pull request by peteruithoven**
See: #698

### CODE REVIEW

**Comment by peteruithoven** [comment]
Ctrl + R also works in browsers. 

Firefox choose to use ctrl+R in their tooltip:
screenshot from 2018-10-23 19 07 55

Other browsers like Epiphany and Chromium don't show shotcuts in their tooltips.

**Comment by peteruithoven** [comment]
Blocked by: https://github.com/elementary/granite/issues/228

**Comment by peteruithoven** [comment]
Maybe we can already merge this and after there is another Granite release with a parse utility we can do another PR?
The build is failing because of: https://github.com/elementary/houston/issues/669

**Comment by jeremypw** [comment]
I cannot merge this till it passes CI :-(

**Comment by peteruithoven** [comment]
@jeremypw the CI issue has been fixed :)

**Pull request merged**
