### PR TITLE
Sidebar Gtk4 Prep

### PR DESCRIPTION
**Pull request by danirabbit**
We can't subclass ListBox in Gtk4 so rework things for that

### CODE REVIEW

**Comment by jeremypw** [comment]
Did you check out the solution in the `gtk4` branch, which avoids repeating code in each listbox?

**Comment by danirabbit** [comment]
I'll need to look at those more closely! I tried a few different things yesterday and wasn't totally satisfied with any direction I was going 😅

**Comment by jeremypw** [comment]
Yes, the `gtk4` branch was intended to provide a possible destination but I am unclear as to what steps along the way would be acceptable.

**Comment by danirabbit** [comment]
Closing in favor of #2287

**Pull request closed without merging**
