### PR TITLE
Port ListModel to Vala

### PR DESCRIPTION
**Pull request by tintou**

### CODE REVIEW

**Comment by tintou** [comment]
@jeremypw This is a huge port, and I don't really get why it's crashing, but the `FileEntry` structure needs to be changed because Vala don't like this…

**Comment by jeremypw** [comment]
Is it not possible to use a (customised) GtkTreeStore for this?

There are all sorts of referencing counting/memory management problems manipulating GLists of TreeIters etc.  At least one crash is due to this.

**Comment by tintou** [comment]
@jeremypw I update this branch to compile and work with master.
This is just a straight port, I propose to redesign it at a later stage.

**Comment by jeremypw** [comment]
@tintou:  This works pretty well! The main issue I have found so far is that in List View there are no expanders and the keyboard shortcut for expanding folders does not work either.

Were you envisaging merging this or the gof-file port first?

**Comment by tintou** [comment]
Closing until it get properly fixed

**Pull request closed without merging**
