### PR TITLE
IconRenderer: thumbnail backgrounds are always iconsize

### LINKED ISSUE #728: Center too-small thumbnails on correctly-sized card
Instead of trying to intelligently resize the whole interactive icon, we should always keep the "icon" size the same, but center any too-small thumbnails (like for small icons) on a background the correct size.

### PR DESCRIPTION
**Pull request by danrabbit**
Drafting because I don't know how to fix list view :upside_down_face: 

Fixes #728

Always render at icon size even if the thumbnail is smaller. Fixes some issues with not being able to see previews under emblems and selection helpers or when the thumbnail is very small or has an extreme aspect ratio

Screenshot from 2022-06-23 20 03 27

### CODE REVIEW

**Comment by jeremypw** [comment]
I think I have fixed issues with List/Column view and emblems now.

**Comment by jeremypw** [comment]
Screenshot from 2022-06-26 10 30 19
Screenshot from 2022-06-26 10 32 18

**Comment by jeremypw** [comment]
@danrabbit Would you like to cast an  eye over my changes for any regressions? Then I will approve.

**Comment by danrabbit** [comment]
@jeremypw thank you for fixing this for me! Really helps a lot in list and column view imo :bowing_woman:

**Pull request merged**
