### PR TITLE
Do not accept drop if location is unmounted

### LINKED ISSUE #2390: Drag N Dropping file on a disk that is not mounted makes the file disappear
### What Happened?

Well, it's rather simple to reproduce. the only thing that will happen is that the file will disappear from it's original location without being copied over to the destination. I ran `grep -Rnw' to search for it but it's gone 

### Steps to Reproduce

1.get a usb or whatever
2. try to drag and drop a file in it when it's still not mounted (eg. there's no "used space" bar under the name of the usb on the sidemenu) 

### Expected Behavior

I would expect it to either make the operation fail completely, or (what most FMs do nowadays I think) mount the target disk automatically and copying the file over

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
don't have any, I might be able to send them tomorrow
```

### Hardware Info

I don't think this has much influence over the files app but..
it's a laptop with an i5-13500H, running the latest i915 drivers shipped by default I guess.

### LINKED ISSUE #2465: Dropping onto mountable bookmark does not work correctly if location mounted after Files starts
### What Happened?

See below.

Caused by the bookmark target location not being updated after it is mounted, only when it is created.

### Steps to Reproduce

1. Start Files
2. Plug in a writable USB drive
3. Mount it
4. Drag a file onto the drive bookmark
5. The file disappears from the source folder but does not appear on the USB drive
6. Look in Home folder - the file has moved there.
7. Press `<Ctrl>Z`   (undo) 0 the file reappears in the source folder.

### Expected Behavior

The file is copied to the USB drive.

### OS Version

8.x (Early Access)

### Software Version

Compiled from git

### Log Output

_No response_

### Hardware Info

_No response_

### PR DESCRIPTION
**Pull request by jeremypw**
Fixes #2390 
Fixes #2465

 * `file_accepts_drop ()` returns false if location unmounted (fixes first issue)
 * Update the target location if mounted after Files started (fixes second issue)
 *

### CODE REVIEW

**Review by danirabbit — APPROVED** [review]

**Review by danirabbit — CHANGES_REQUESTED** [review]
Can you resolve conflicts? It looks like maybe this function moved in another commit

**Comment by jeremypw** [comment]
Conflict fixed

**Comment by danirabbit** [comment]
@jeremypw ah this is a +/-0 diff now :sweat_smile: That doesn't seem right

**Comment by jeremypw** [comment]
Looks like `libcore/FileUtils` was moved elsewhere in `main` so need to rewrite this branch if the issue persists.

**Comment by jeremypw** [comment]
Noticed a related issue - the volume bookmarks only have a valid target file if they are already mounted when Files window is opened. In main, the target file is not updated if the volume is subsequently mounted so dropping a file on it still does not work in this branch.  This is now fixed by updating the target file whenever the volume is mounted or unmounted.

**Comment by jeremypw** [comment]
@danirabbit This is now ready for review hopefully.

**Comment by jeremypw** [comment]
Converting to draft to investigate bug where a (copy) file is created in the current working folder when Files is being run in a terminal and the file is dropped onto an unmounted volume.

**Comment by jeremypw** [comment]
For now, I have not implemented auto-mounting of unmounted volumes when dropped on. This could be implemented in a further PR if thought desirable.

**Comment by jeremypw** [comment]
> Converting to draft to investigate bug where a (copy) file is created in the current working folder when Files is being run in a terminal and the file is dropped onto an unmounted volume.

I am no longer sure how to reproduce this bug so a shorter PR has been proposed omitting the related commit.

**Comment by jeremypw** [comment]
Closing in favour of #2466 and #2468

**Pull request closed without merging**
