### PR TITLE
Fix on_icon and on_helper in TreeView for RTL layout

### LINKED ISSUE #178: Helpers do not work in ListView when RTL
When using an RTL language, the helpers do not work in ListView (they work in IconView).

### PR DESCRIPTION
**Pull request by jeremypw**
Fixes #178 

TO TEST
* Use single-click mode
* Run Files in a RTL environment (e.g. LANGUAGE=ar_DZ.UTF.8  io.elementary.files if not already RTL)
* Check that all zones in ListView are correctly identified (on_icon, on_helper, on_name on_blank etc).

### CODE REVIEW

**Comment by donadigo** [comment]
Unfortunately can't test this because in RTL, when switching to list view, Files crashes.

**Comment by jeremypw** [comment]
As discussed, please test by specifying an RTL locale in the command-line, not using Gtk Inspector (although I do not get a crash either way).

**Comment by donadigo** [comment]
This branch doesn't compile right now:
```
/home/donadigo/Projects/files-rtl-helpers/libwidgets/Chrome/ButtonWithMenu.vala:91.9-91.34: warning: Type `Marlin.View.Chrome.ButtonWithMenu.MenuFetcher' can not be used for a GLib.Object property
        public MenuFetcher fetcher {
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation succeeded - 7 warning(s)
Scanning dependencies of target pantheon-files-widgets
[ 29%] Building C object libwidgets/CMakeFiles/pantheon-files-widgets.dir/Interfaces/LocatableInterface.c.o
[ 29%] Building C object libwidgets/CMakeFiles/pantheon-files-widgets.dir/Interfaces/NavigatableInterface.c.o
[ 30%] Building C object libwidgets/CMakeFiles/pantheon-files-widgets.dir/Chrome/BasicLocationBar.c.o
[ 31%] Building C object libwidgets/CMakeFiles/pantheon-files-widgets.dir/Chrome/BasicBreadcrumbsEntry.c.o
[ 32%] Building C object libwidgets/CMakeFiles/pantheon-files-widgets.dir/Chrome/BreadcrumbElement.c.o
/home/donadigo/Projects/files-rtl-helpers/libwidgets/Chrome/BreadcrumbElement.vala: In function ‘marlin_view_chrome_breadcrumb_element_instance_init’:
/home/donadigo/Projects/files-rtl-helpers/libwidgets/Chrome/BreadcrumbElement.vala:70:2: error: conversion to non-scalar type requested
     private Gtk.Border padding = Gtk.Border ();
```

**Comment by jeremypw** [comment]
Compilation problem with valac 0.40 fixed by a recent separate merge.

**Pull request merged**
