### PR TITLE
filechooser-portal: Make sure that we are getting the response signal before destroy

### PR DESCRIPTION
**Pull request by tintou**
Also use the GtkDialog before the end of the response block as it will be destroyed.

### CODE REVIEW

**Comment by tintou** [comment]
Fixes #1518

**Comment by jeremypw** [comment]
This works when opening a file (using flatpak'd version of code) however, when trying to use it to save a file with Code I get: `Document.vala: File "(null)" saved successfully` and the tab label becomes blank.  No file is saved (where expected).   Not sure how much of this due to an issue with the Code flatpak though.  I'll try with a different flatpak.  Note that this test was performed __after__ removing the pantheon-filechooser module to ensure that the portal was used.
`

**Comment by tintou** [comment]
@jeremypw that might be another bug, I'm fixing the open file method here, not the save one so that might be something to look at afterward

**Comment by jeremypw** [comment]
OK, I'll merge this then and file another issue re saving files.

**Review by jeremypw — APPROVED** [review]
Fixes opening files

**Pull request merged**
