### PR TITLE
Ensure cursor follows helper selection without losing existing selection

### PR DESCRIPTION
**Pull request by jeremypw**
This makes IconView and TreeView behave the same way when the cursor is moved with the keyboard after making a selection using the helpers and mouse.

In master, the treeview behaves differently to icon view - the former does not move the cursor to the last selected item whereas iconview does (this is due to differences in Gtk implementation).

In this PR, the cursor moves to last selected without losing the existing selection in all views (in treeview the selection is remembered and reestablished after moving the cursor).

This fixes part of #330

### CODE REVIEW

**Comment by jlnr** [comment]
Ah, I see now. This works and fixes my issue when using the helper badge, but the keyboard cursor is not updated when using a selection rectangle (which I often do even for single files). Is the difference between both interactions intentional?

**Comment by jeremypw** [comment]
I found dealing with rubberband selections difficult so I left it for another day.  In IconView it not so clear which will be the last item selected when doing a rectangular selection.

**Comment by jeremypw** [comment]
Whereas helper selection is handled by Files code, rubberband selection is handled by the Gtk Widget which complicates matters.

**Comment by jlnr** [comment]
Makes sense, thanks.

**Pull request merged**
