### PR TITLE
Release 6.1.0

### PR DESCRIPTION
**Pull request by danrabbit**
Drafting, if @jeremypw wants to list some things to prioritize reviews on next week :)

- [x] https://github.com/elementary/files/pull/1899

### CODE REVIEW

**Comment by jeremypw** [comment]
It would be good it the following could be finalized (starting with the easiest)

 - #1847
 - #1832 
 - #1848 

Hopefully I'll be able to review and approve the recent fixes to the filechooser portal before the end of the month.

The sidebar PR still needs testing/dogfooding on a wider range of systems before release.  Need to decide what to do about empty unformatted drives/partitions.

**Comment by jeremypw** [comment]
The branch #1894 can be used to dogfood several fixes simultaneously.

**Comment by danrabbit** [comment]
Since this isn't released yet, would be nice to get in https://github.com/elementary/files/pull/1912

**Comment by jeremypw** [comment]
Another small fix that would be nice to squeeze in would be #1907.

**Review by cassidyjames — APPROVED** [review]

**Pull request merged**
