### PR TITLE
Swipe back forward

### PR DESCRIPTION
**Pull request by jeremypw**
Partial fix for #588 (part 2)

An experimental branch implementing simple swipe detection in the Marlin.View.Window and linking to some actions.

This could only be tested with mouse swipes on the author's machine.  Needs testing on a touch enabled machine.

### CODE REVIEW

**Comment by danrabbit** [comment]
With any number of fingers I just get rubberband selection :(

**Comment by danrabbit** [comment]
Same results unfortunately. FWIW, I get this on startup:
```
(io.elementary.files:22321): GLib-GObject-WARNING **: 15:12:33.938: ../../../../gobject/gsignal.c:2423: signal 'swipe' is invalid for instance '0x564b33c5f520' of type 'GObject'
```

**Comment by jeremypw** [comment]
OK, thanks for trying.  I'll probably leave this until I can test properly myself.

**Comment by jeremypw** [comment]
I am withdrawing this for now - will not be able to progress for a while.

**Pull request closed without merging**
