### PR TITLE
[Gtk4Prep] Remove Gdk.beep ()

### PR DESCRIPTION
**Pull request by jeremypw**
Gdk.beep () does not exist in Gtk4

### CODE REVIEW

**Comment by danirabbit** [comment]
Looks like it's just been moved to be per display https://valadoc.org/gtk4/Gdk.Display.beep.html

**Comment by jeremypw** [comment]
@danirabbit  Ah, thanks. If we keep this, should it respect the `org.gnome.desktop.sound event-sounds` setting? I am not keen on in-app beeps when the user's attention doesn't need attracting - they do not give any further information.

**Comment by danirabbit** [comment]
@jeremypw beep is used when there was some kind of input but the task can't be completed. Like when you're in an empty text entry and try backspace. It's acknowledging the input was accepted but there's nothing to do in response to it.

I think it should respect the settings for alert sounds and screen flashing automatically

**Comment by jeremypw** [comment]
OK, thanks.  I'll leave this in then.

**Pull request closed without merging**
