### PR TITLE
Changed colours for file tags

### LINKED ISSUE #155: File tagging should use elementary colours.
The file tagging colours should be from the elementary colour palette and not tango's.
file-highlights

### PR DESCRIPTION
**Pull request by TraumaD**
Fixes #155 

Changed file tag colours to colours from elementary's palette.
screenshot from 2017-10-10 16 44 37
screenshot from 2017-10-10 16 39 31

### CODE REVIEW

**Comment by danrabbit** [comment]
I wonder if it would be better to use Material brown as a stopgap. It would be closer to what users are expecting. It looks like you're using 100 to make sure the black text is legible. Maybe Material Brown 100 (#D7CCC8) or 200 (#BCAAA4) would work here

**Comment by TraumaD** [comment]
That sounds good to me. I'll play around with material brown. I can make the changes and update the PR when I get back to my computer.

**Comment by TraumaD** [comment]
Does anyone have a preference on which brown to use?
tag-colours
tag-dialog

**Comment by danrabbit** [comment]
200 is probably more distinctly brown and not just grey looking

**Comment by TraumaD** [comment]
I was thinking the same. 100 looks a little too grey. just wanted to run it by someone else before going for it.

**Comment by jeremypw** [comment]
@TraumaD   Thanks for your contribution! May it be the first of many ;-)

**Pull request merged**
