### PR TITLE
Focus padding

### LINKED ISSUE #82: Excessive padding in focus rectangle
Since r2581, the padding in the focus rectangle (Icon View) has increased and this causes touching/overlap with the icon for some icons. Padding should be reduced to original value.

### PR DESCRIPTION
**Pull request by jeremypw**
Fixes #82

### CODE REVIEW

**Comment by jeremypw** [comment]
Need confirmation as to to how tightly the focus rectangle should fit the text.

**Comment by danrabbit** [comment]
It looks like the padding is uneven:

screenshot from 2017-10-18 12 42 58

And there's some clipping issues:

screenshot from 2017-10-18 12 43 15

**Comment by jeremypw** [comment]
The subsequent merges from master appear to have caused a regression. Will fix.

**Comment by jeremypw** [comment]
Replaced with new branch "focus-rect"

**Pull request closed without merging**
