### PR TITLE
Remove deprecation: button.xalign; bump min gtk, disable deprecated

### PR DESCRIPTION
**Pull request by jeremypw**
First step towards GTK4 - remove remaining GTK3  deprecations.  Note that needs https://github.com/elementary/granite/pull/545 to suppress warning about a deprecation in DynamicNotebook

### CODE REVIEW

**Comment by danrabbit** [comment]
Hm, so I think the reason this was done was to make it so clicking anywhere along the actionbar will activate the button. If we want to preserve that behavior, it looks like according to the docs that the child of the button should be a Gtk.Alignment and we can set `xalign` there instead of on the button itself

**Comment by jeremypw** [comment]
@danrabbit OK, I can do that.  I left it like this because Code does not hexpand the button - although in that case there is a menu button on the right.

**Comment by jeremypw** [comment]
@danrabbit Slight problem - `Gtk.Alignment` is deprecated and does not appear in Gtk4. I'll see if there is another solution.

**Comment by jeremypw** [comment]
Closing - fix xalign better in another PR.

**Pull request closed without merging**
