### PR TITLE
Click mode menu

### PR DESCRIPTION
**Pull request by jeremypw**
Based on #1036.  Expose the two click modes in a simple AppMenu.

Some design input is expected.  At the moment radio buttons are used as we may wish to add a third 'mixed' mode. But if that is not the case, then a simple switch may be more appropriate.

### CODE REVIEW

**Comment by m93a** [comment]
@danrabbit Bump. Any news on this?

**Comment by jeremypw** [comment]
Blocked for release of v4.4.0

**Comment by jeremypw** [comment]
Probably better to remove the new mixed mode option from this PR to make it more likely to be reviewed/approved.

**Comment by jeremypw** [comment]
Closing pending input on whether (a) a mixed mode and (b) app menu is acceptable.

**Pull request closed without merging**
