### PR TITLE
Sushi experiment

### PR DESCRIPTION
**Pull request by jeremypw**
Experimental branch - not for merging

### CODE REVIEW

**Comment by marbetschar** [comment]
That's pretty cool stuff!! The styling of Sushi just looks out of place and its window jumps around after starting - but otherwise this works suprisingly well :)

**Comment by jeremypw** [comment]
Maybe if the correct window handle parameter is passed the jumping around would be fixed.  I believe that (on X) the `xid` of the FIles window is needed. Not sure what happens with Wayland though.

**Comment by jeremypw** [comment]
Doesn't look like there is a way to get the xid of a Gdk.Window anymore.  Anyway Sushi needs to be made backend agnostic.

**Comment by jeremypw** [comment]
If the UX team were to OK a preview function we would probably want it to be in a sidebar not provided by a third party app so I am closing this for now.

**Pull request closed without merging**
