### PR TITLE
Module: only use memory if a FileChooserDialog is in use

### PR DESCRIPTION
**Pull request by tintou**
By default, the module was always using memory, even if the application wasn't using any FileChooserDialog. It is now also freeing any used memory after all the dialogs are freed.

### CODE REVIEW

**Comment by jeremypw** [comment]
The custom filechooser seems not to be working for me at the moment (always get standard gtk file chooser).  This module is supposed to be replaced by a NativeFileChooser interface at some point.

**Comment by tintou** [comment]
@jeremypw for me,`echo $GTK_MODULES` outputs `:pantheon-filechooser-module:gail:atk-bridge`
is it your case ?

**Comment by jeremypw** [comment]
@tintou: Yes, the same.  but e.g. opening a file with the Code headerbar button brings up the gtk file chooser.

**Comment by tintou** [comment]
weird, it's working here

**Comment by jeremypw** [comment]
It is not working with a 'clean' install of Juno stable either (for me) ?!

**Comment by jeremypw** [comment]
Running Code with --gtk-module=pantheon-filechooser-module gives no error but still does not give the custom chooser dialog.

**Comment by jeremypw** [comment]
Just installed the April unstable iso on a new laptop and still no custom FileChooser using Code :-(

**Comment by jeremypw** [comment]
Hmm. Now the custom FIleChooser is working again on the unstable Juno install, but not on the stable install.  I have just installed some dev related software as well as the chromium browser.

**Pull request merged**
