### PR TITLE
SidebarWindow: Use button in actionbar instead of ActionRow

### PR DESCRIPTION
**Pull request by danrabbit**
Actionbars in Sidebars are not currently styled, but that's an issue with Greenfield

* Since this isn't in a listbox anymore, seems much simpler to use a regular Gtk.Button.
* Added `…` since this opens a new dialog before creating a new item
* Removed redundant text from the tooltip

### CODE REVIEW

**Review by jeremypw — CHANGES_REQUESTED** [review]
Makes sense.  My only query is whether the button should remain focused after clicked and whether it should fill the whole row.

If there are more actions in future we might want to change to a Code-like actionbar.

**Comment by danrabbit** [comment]
Yeah that's just default focus handling in Gtk

I don't think we have any precedent for expanding buttons in actionbars to fill the entire space

Can you elaborate on what you mean by there being a difference in Code's actionbar?

**Comment by jeremypw** [comment]
The focussing issue can be fixed (if wished) by the setting `can-focus` property to `false`. There doesn't seem to be a good reason to focus on this button. If the button does not focus it does not matter if it does not hexpand.

The Code Actionbar is thinner, has only icons (with tooltips) and is paler. The focus issue is present but less obtrusive.

Files Actionbar (focused)
FilesActionBar

Code Actionbar (focused)
CodeActionBar (1)

**Comment by danrabbit** [comment]
Ah okay I see. Yes there's a missing style class. I'll fix that

Interactive elements needs to be focusable for keyboard navigation :)

**Comment by jeremypw** [comment]
Oh I forgot that :disappointed:  There is a keyboard shortcut but its not very discoverable with the keyboard I guess.

**Comment by danrabbit** [comment]
Okay, I proposed a branch to style flat actionbars in Greenfield here: https://github.com/elementary/stylesheet/pull/800

I also moved the flat class to the actionbar and made the icon symbolic. This is how it looks in Greenfield:

Screenshot from 2020-09-01 11 42 19@2x

I'm sure it's rather broken in the old stylesheet :sweat_smile:

**Comment by cassidyjames** [comment]
@jeremypw also fwiw we're slowly but surely adding action text to those inline toolbar actions to make them more discoverable and accessible without a tooltip. So what's more likely is for Code to change to look a little more like this ;)

**Comment by danrabbit** [comment]
Updated with the latest Greenfield revision for less vertical padding

Screenshot from 2020-09-01 16 36 15@2x

**Review by jeremypw — APPROVED** [review]
Yes, that looks much better - thanks.

**Pull request merged**
