### PR TITLE
Add AppMenu button to headerbar

### LINKED ISSUE #2123: Files should have a settings/cog wheel menu in the headerbar
### Problem

1. Since there are now three settings options in the context menu, it is starting to feel too cramped.
2. Since the settings are global for the app, they have no place in the context menu for a given folder, it would be different if those settings where pertaining to the folder currently opened.
3. With a settings menu we could also expand on the available settings, like the missing icon size/viewport zoom setting, which is accessible through a keyboard/ keyboard + mouse wheel combination but is not teached, hinted or conveyed to the user in any way. Also, a theme setting to follow the system defined dark/light mode or have one independent.

### Proposal

A way to address all those issues would be to place a pop up settings/cog wheel menu in the headerbar.

### Prior Art (Optional)

There are already several default apps that follow this design pattern:
- Code
- Terminal
- Mail

### PR DESCRIPTION
**Pull request by jeremypw**
Fixes #2123 

 - [x] Zoom controls
 - - [x]  Update label of "normal" button (?)
 - - [x] Make zoom insensitive when at max/min zoom
 - [x] Undo/Redo controls
 - [x] Global boolean options
 - - [x] Selection mode for folders
 - - [x] Show/hide hidden files  
 - - [x] Show/hide remote thumbnails
 - - [x] Show/hide local thumbnails
 - - [x] Sort directories first
 - [x] Remove corresponding  context menu items (TBD)

Left for possible future PRs

Screenshot from 2023-02-11 21 01 40
Screenshot from 2023-02-11 21 00 37

### CODE REVIEW

**Comment by jeremypw** [comment]
@danirabbit A few questions to resolve regarding this PR: 

 * How to handle labelling of "normal zoom" button. Should it change like in Code and Terminal, in which case how to denote the icon size relative to "normal"?  Or is it OK to leave it with a fixed label or icon?
 * What is optimum order of the boolean option switches.
 * Is there a need/demand to override the system style in Files?  Terminal and Code widgets have their own built-in style handling but for Files this is not the case.

Please apply your design expertise to the appearance.

**Comment by danirabbit** [comment]
@jeremypw this looks awesome!
> How to handle labelling of "normal zoom" button. Should it change like in Code and Terminal, in which case how to denote the icon size relative to "normal"? Or is it OK to leave it with a fixed label or icon?

I think using percentages still makes sense here since we have some views with lots of options that saying like "extra small" or "extra large" starts to get meaningless. I think we should still adjust the label to match what is in the view to be consistent here.

> What is optimum order of the boolean option switches.

I proposed https://github.com/elementary/files/pull/2133 with a few suggested changes to organization/structure/appearance

> Is there a need/demand to override the system style in Files? Terminal and Code widgets have their own built-in style handling but for Files this is not the case.

I don't think so? The reason that Code/Terminal have these manual overrides is because they're using syntax highlighting schemes where people have pretty strong preferences about using dark/light syntax highlighting separate from the rest of the system. I'm not sure that similar demand exists for other apps

> Is it OK to remove the corresponding menuitems from the directory context menu?

Yes! I think we should definitely clean those up so that menu can become simpler

**Comment by danirabbit** [comment]
Ah something else I noticed is that the zoom actions don't become disabled when they git their min/max values. So for example, the zoom in button is still sensitive even when we're at the max zoom and pressing it has no effect

**Comment by jeremypw** [comment]
@danirabbit Thanks for the comments! I'll get on with implementing those tomorrow.

**Comment by danirabbit** [comment]
Oh, actually I'm curious about the "Sort Folders Before Files" option. Is there a reason you wanted to move that here instead of having it with the other sort options in the context menu?

**Comment by jeremypw** [comment]
> Oh, actually I'm curious about the "Sort Folders Before Files" option. Is there a reason you wanted to move that here instead of having it with the other sort options in the context menu?

This is because that is a global option affecting all folders and the file chooser.  The other sort options only affect the individual folder you set them on (because in that case they are stored in the file metadata).

**Comment by danirabbit** [comment]
I think that one still makes sense to have in the context menu with the other sort options, even if we duplicate it in both locations. But just to make sure sorting options are all available at once and someone won't be confused about where to find this when they're changing other sorting options

**Comment by jeremypw** [comment]
> I think that one still makes sense to have in the context menu with the other sort options, even if we duplicate it in both locations. But just to make sure sorting options are all available at once and someone won't be confused about where to find this when they're changing other sorting options

I have no problem with duplicating it in the context menu.

**Review by danirabbit — CHANGES_REQUESTED** [review]
It looks like the "local-thumbnails" check is always disabled when files starts. Somewhere along the way action state isn't being set on startup

**Comment by jeremypw** [comment]
> It looks like the "local-thumbnails" check is always disabled when files starts. Somewhere along the way action state isn't being set on startup

Seems that was a pre-existing bug that this PR exposes.  Now fixed.

**Review by danirabbit — APPROVED** [review]
Let's go! :rocket: 

Great work :)

**Pull request merged**
