### PR TITLE
Window: don't get position

### PR DESCRIPTION
**Pull request by danirabbit**
We're not able to get window position in Gtk4. It also doesn't appear we do anything with tiling information anyways, so remove all the unused stuff.

Get maximized state from Gtk.Window and make a note about get fullscreen state here in the future as well

### CODE REVIEW

**Review by jeremypw — COMMENTED** [review]
This PR no longer saves and restores the tiled state of the window - is that the intention?  It seems odd that when closing a tiled Files window, reopening it restores it to the centre of the screen but with the same size as a tiled window.

**Comment by danirabbit** [comment]
@jeremypw afaict we never restored tile state. The tiling state behavior should be the same as in main, but I pushed a commit to only save window size if we're neither maximized nor tiled

**Comment by jeremypw** [comment]
I tried it out it out in main and does appear to work, but by positioning the window so it is pseudo-tiled.  This will not work in Gtk4 :frowning_face: so will have to be accepted.

**Review by jeremypw — APPROVED** [review]
I think this is a reasonable solution.

**Pull request merged**
