### PR TITLE
Prefer dark

### PR DESCRIPTION
**Pull request by danrabbit**

### CODE REVIEW

**Comment by jeremypw** [comment]
There are (at least) a couple of issues with Files and dark theme:
* Outline of breadcrumbs not visible
* Outline of view switcher buttons not visible.

**Comment by danrabbit** [comment]
There are still outstanding issues here with icons that I consider blockers. I don't think this is ready for review

**Comment by cassidyjames** [comment]
@danrabbit we have a couple open on the icons repo, but those are outside the scope of Files imho. Is there anything in Files that's still blocking it?

**Comment by danrabbit** [comment]
@cassidyjames Not that I'm aware of, but I still wouldn't consider merging this until those issues are fixed. I'm going to move this back to draft so it doesn't get accidentally merged pre-maturely

**Comment by cassidyjames** [comment]
Blocked by https://github.com/elementary/icons/issues/853

**Comment by danrabbit** [comment]
Unblocking per conversation in standup

**Review by cassidyjames — APPROVED** [review]

**Pull request merged**
