### PR TITLE
Bulk Rename: Use ModeButton for basename options

### PR DESCRIPTION
**Pull request by jeremypw**
Partially addresses #2194

### CODE REVIEW

**Comment by danirabbit** [comment]
I haven’t built this yet, but ModeButton is removed in Gtk4 so I’m not sure it’s a good idea to introduce a new one

**Comment by jeremypw** [comment]
@danirabbit Ah - I forgot that. I'll try and do it a Gtk4 compatible way - or do you want to leave it as it is?

**Comment by jeremypw** [comment]
Screenshot from 2023-05-14 12 18 17

**Review by danirabbit — APPROVED** [review]
LGTM!

**Pull request merged**
