### PR TITLE
Release 8.0.0

### PR DESCRIPTION
**Pull request by danirabbit**
Todo:
- [x] Update app menu screenshot

### CODE REVIEW

**Comment by danirabbit** [comment]
This is still building for Jammy in daily, so need to double check why this was bumped to 8 instead of maybe 6.6? or 7 maybe? Trying to get major version numbers to match the oldest release it builds for

**Comment by danirabbit** [comment]
Ah might have been because of wallpaper portal, but we did release new portals for Jammy

**Comment by jeremypw** [comment]
Are you reserving 8.x version numbers for Gtk4 ports? It is a rather large bump.

**Comment by danirabbit** [comment]
@jeremypw Yeah I'm trying to match the major version number to the oldest release we're still building for. Just makes it easy to know at a glance what I need to build/test on. I think this should be okay to release to 7.1?

**Comment by danirabbit** [comment]
Okay yup as far as I can tell this still works on OS 7.1 so bumped the release version down to 7.0.0

**Comment by danirabbit** [comment]
@jeremypw Is this okay to release or any branches blocking currently?

**Comment by jeremypw** [comment]
@danirabbit There are no blocking branches as far as I am concerned - please go ahead.

**Pull request merged**
