### PR TITLE
Fix linear selection with mixed-mode

### LINKED ISSUE #1948: Selecting files with shift + arrow keys has imprecise behavior
### What Happened?

Selecting files with shift + arrow keys has imprecise behavior

### Steps to Reproduce

1. Select a file by clicking on it.
2. Press "shift" + "left or right" keys.
Result: Sometimes it does nothing. In others it selects more than one file at a time (sometimes it does it in reverse order).

### Expected Behavior

It should work fine.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

_No response_

### Hardware Info

_No response_

### PR DESCRIPTION
**Pull request by jeremypw**
Fixes #1948

### CODE REVIEW

**Comment by danrabbit** [comment]
Is this still relevant now that clicking labels activates?

**Comment by jeremypw** [comment]
Hmm, there is only one small material difference which makes the cursor follow the last selection.  Not sure how essential that was now.  I'll check.

**Comment by jeremypw** [comment]
I can confirm the specific issue described at https://github.com/elementary/files/issues/1948#issuecomment-997227394 still exists in master (when clicking on the name to select) and this PR fixes it.

**Comment by danrabbit** [comment]
Ah yep, I'm not sure what I missed when I was looking at this before, but I can confirm this fixes the issue in all views. Nice work!

**Review by danrabbit — APPROVED** [review]

**Pull request merged**
