### PR TITLE
Launch commands in terminal so can see output

### PR DESCRIPTION
**Pull request by jeremypw**
May address #2010 

* Always execute files other than desktop files in terminal so can see any output.
* Launch with context like Nautilus
* Set PWD of context to executable's folder

For simplicity all executables are launched in terminal.  If required a dialog could be thrown asking whether to launch in terminal (like Nautilus).

To be considered - any possible security implications - warning required?  Note that activating the item will not run it automatically - this requires choice from the context menu.  However, at the moment, dropping a file onto a script *does* run it so that probably needs some user input to confirm.

### CODE REVIEW

**Comment by jeremypw** [comment]
Thanks for trying! The PWD should be set to the location of the executable at least until the process ends by the line `context.setenv ("PWD", FileUtils.get_parent_path_from_path (path));` but maybe that is not working. That should not cause the library not being found though, if it is in one of the folders listed in your PATH variable.  Do you know where `libsteam_api.so` is stored on your computer?  If you open a terminal in the executable folder and launch the executable manually does it work?

If you launch the exec

**Comment by ChildishGiant** [comment]
Yeah, launching through the terminal in the executable folder works. libsteam_api.so is located next to the executable but because it's not being launched from the pwd it can't be found.

**Comment by jeremypw** [comment]
I think this problem with this PR is at least partially due to a bug in elementary Terminal.  See  https://github.com/elementary/terminal/pull/477/  It might be necessary for that PR to be merged for this solution to work.

**Comment by jeremypw** [comment]
Ignore the "thread-safe" and other warnings - they seem to be due to upstream bugs, not this PR.

**Comment by jeremypw** [comment]
Hmm, I put both the executable and path in quotes so the spaces should not have been a problem but admittedly my test script/path did not have spaces.  I'll test again with spaces.  Thanks for testing again - we are making progress!

**Comment by jeremypw** [comment]
@ChildishGiant I have made a workround for the spaces issue so that this PR works with the existing Terminal.  It would be better fixed by improving the way Terminal runs programs but it is hard to get Terminal PRs reviewed.

**Review by zeebok — DISMISSED** [review]
This looks good to me. I trust any significant testing was already between the two of you.

**Comment by jeremypw** [comment]
@zeebok Thanks for having a look at this! It occurs to me now I have looked at it again after a break that it assumes that `io.elementary.terminal` is installed.  While this is usually the case I guess it is possible that the user has replaced it with a different terminal.  I should provide a fallback for that situation.

**Comment by jeremypw** [comment]
Marked as blocked as changes to Terminal seem to prevent work around for spaces in path from working at the moment and no alternative work around immediately obvious.  Will probably require a fix to Terminal to be merged first.

**Comment by BAProductions** [comment]
Threw it’s called backslash!!!!

**Comment by jeremypw** [comment]
@BAProductions The problem seems to lie in `Shell.parse_argv (program_string, out program_with_args);` in Terminal.  This interprets backslashes literally.  However, if you have a more detailed solution please advise.

**Pull request closed without merging**
