### PR TITLE
Fix sort order after file operations

### LINKED ISSUE #2179: Refresh of sort order doesn't happen automatically
### What Happened?

Hi everyone,

[default file system, default partionning scheme]

Using pantheon-files, I'm on ~/Downloads . I just finished downloading a .zip . The icon of the archive ("divers 2023-001.zip") doesn't look like an archive type icon + I still get the associated .part file, yet the download has been completed.
Then I navigate somewhere else and come back to  ~/Downloads, only then the view is refreshed, with correct icon and no more .part file.

I can reproduce it anywhere on my desktop, with any file (when I edit any file, a cached file shows up but it doesn't disappear when I close the file I've edited)

i.e I'm in ~/ , I open .zshrc (so, with Code, by default, but I don't think it's relevant here) . I close .zshrc , I still see several LOCK files in the view but they're don't exist anymore ( `ls -a` doesn't list them)
I change the view in files (i.e I go to Downloads),  then I come back to ~/ , and only there the view has been refreshed and the LOCK files aren't present anymore in the view.

I don't know if it's linked to #36 , that issue dates from june 2017 so I prefered to fill a new issue.

A) a .zip archive

1) after the download is finished

Capture d'écran du 2023-05-01 08 28 43

2) when I refresh the view by coming back to the folder

Capture d'écran du 2023-05-01 08 29 01

B) opening ~/.zshrc

1) before opening

Captures d'écran de 2023-05-01 10 32 48

2) after opening

Captures d'écran de 2023-05-01 10 35 05

3) after closing

Captures d'écran de 2023-05-01 10 35 21

4) after refreshing the view by navigating somewhere else and coming back into the folder

Captures d'écran de 2023-05-01 10 37 26

### Steps to Reproduce

1. Using pantheon-files, go to any folder
2.  Edit a file, so a cache file (LOCK) is created
2.b Or download a file on the web, so a part file (.part) is created
3. Finish editing the file (close your editor) 
3.B Or wait for the download process to finish
4. You'll see (well, I'm seeing :) ) that the cache file/the part file is still present in the view

### Expected Behavior

In pantheon-files, the view should automatically refresh after the action (editing a file, downloading an archive...) is finished

[the attached logs : 1) open ~/.zshrc 2) close ~/.zshrc (all the LOCK files should automatically disappear  from the view but they're still present - they aren't physically present on my hard drive (the ls -a command doesn't show them)

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
** (io.elementary.files:20052): DEBUG: 10:17:16.102: Directory.vala:1167: Dir file:///home/ben/.zcompdump-ben-laptop-5.8.1.lock not in cache
** (io.elementary.files:20052): DEBUG: 10:17:16.102: Directory.vala:894: query info failed, Erreur lors de l’obtention des informations du fichier « /home/ben/.zcompdump-ben-laptop-5.8.1.lock » : Aucun fichier ou dossier de ce type file:///home/ben/.zcompdump-ben-laptop-5.8.1.lock

** (io.elementary.files:20052): CRITICAL **: 10:17:16.102: Directory.vala:914: FILE INFO null

** (io.elementary.files:20052): CRITICAL **: 10:17:16.102: files_file_update: assertion '_tmp0_ != NULL' failed
** (io.elementary.files:20052): DEBUG: 10:17:16.103: Directory.vala:894: query info failed, Erreur lors de l’obtention des informations du fichier « /home/ben/.zcompdump-ben-laptop-5.8.1.lock » : Aucun fichier ou dossier de ce type file:///home/ben/.zcompdump-ben-laptop-5.8.1.lock

** (io.elementary.files:20052): CRITICAL **: 10:17:16.103: files_file_update: assertion '_tmp0_ != NULL' failed
** (io.elementary.files:20052): DEBUG: 10:17:16.190: Directory.vala:1167: Dir file:///home/ben/.zsh_history.LOCK not in cache
** (io.elementary.files:20052): DEBUG: 10:17:16.191: Directory.vala:894: query info failed, Erreur lors de l’obtention des informations du fichier « /home/ben/.zsh_history.LOCK » : Aucun fichier ou dossier de ce type file:///home/ben/.zsh_history.LOCK

** (io.elementary.files:20052): CRITICAL **: 10:17:16.191: Directory.vala:914: FILE INFO null

** (io.elementary.files:20052): CRITICAL **: 10:17:16.191: files_file_update: assertion '_tmp0_ != NULL' failed
** (io.elementary.files:20052): DEBUG: 10:17:16.191: Directory.vala:894: query info failed, Erreur lors de l’obtention des informations du fichier « /home/ben/.zsh_history.LOCK » : Aucun fichier ou dossier de ce type file:///home/ben/.zsh_history.LOCK

** (io.elementary.files:20052): CRITICAL **: 10:17:16.191: files_file_update: assertion '_tmp0_ != NULL' failed
** (io.elementary.code:20101): DEBUG: 10:17:16.794: Document.vala:935: Could not find mount location
(io.elementary.code:20101): dconf-DEBUG: 10:17:48.360: change_fast
(io.elementary.code:20101): dconf-DEBUG: 10:17:48.360: change_fast
(io.elementary.code:20101): dconf-DEBUG: 10:17:48.360: change_fast
(io.elementary.code:20101): dconf-DEBUG: 10:17:48.360: change_notify: /io/elementary/code/saved-state/window-position
(io.elementary.code:20101): dconf-DEBUG: 10:17:48.360: change_fast
(io.elementary.code:20101): dconf-DEBUG: 10:17:48.360: change_fast
** (io.elementary.code:20101): DEBUG: 10:17:48.360: Document.vala:377: Closing ".zshrc"
** (io.elementary.code:20101): DEBUG: 10:17:48.360: Document.vala:873: Backup file deleting: /home/ben/.zshrc~
** (io.elementary.code:20101): DEBUG: 10:17:48.360: Document.vala:876: Backup file doesn't exists: /home/ben/.zshrc~

(io.elementary.code:20101): GLib-GObject-WARNING **: 10:17:48.374: ../../../gobject/gsignal.c:2765: instance '0x56260be6f1b0' has no handler with id '566'
(io.elementary.code:20101): dconf-DEBUG: 10:17:48.380: change_fast
(io.elementary.code:20101): dconf-DEBUG: 10:17:48.382: unwatch_fast: "/io/elementary/code/saved-state/" (active: 2, establishing: 0)
(io.elementary.code:20101): dconf-DEBUG: 10:17:48.384: sync
** (io.elementary.files:20052): DEBUG: 10:17:48.395: Directory.vala:1167: Dir file:///home/ben/.zsh_history.LOCK not in cache
** (io.elementary.files:20052): DEBUG: 10:17:48.395: Directory.vala:894: query info failed, Erreur lors de l’obtention des informations du fichier « /home/ben/.zsh_history.LOCK » : Aucun fichier ou dossier de ce type file:///home/ben/.zsh_history.LOCK

** (io.elementary.files:20052): CRITICAL **: 10:17:48.396: Directory.vala:914: FILE INFO null

** (io.elementary.files:20052): CRITICAL **: 10:17:48.396: files_file_update: assertion '_tmp0_ != NULL' failed
** (io.elementary.files:20052): DEBUG: 10:17:48.396: Directory.vala:894: query info failed, Erreur lors de l’obtention des informations du fichier « /home/ben/.zsh_history.LOCK » : Aucun fichier ou dossier de ce type file:///home/ben/.zsh_history.LOCK

** (io.elementary.files:20052): CRITICAL **: 10:17:48.396: files_file_update: assertion '_tmp0_ != NULL' failed
```

### Hardware Info

Dell XPS 13 L322X

### LINKED ISSUE #2271: Weird file appeared alongside an edited text file ended with ~
### What Happened?

Weird text file appeared alongside my own text file called finished with ~ when I saved what I wrote

### Steps to Reproduce

1. I create a text file
2. I open (Pressing enter not double click) the text file and adding/modifing the content in it
3. Save it
4. Another text file appeared alongside the original one got the same name ended with ~
5. I think that the file manager should do an autorefresh after saving a text file to not showing the same file ended with ~
### Expected Behavior

The file manager should autorefresh itself to hiding the ~ file 😐 
### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Log Output

_No response_

### Hardware Info

```
System:
  Host: dell-latitude Kernel: 5.19.0-50-generic x86_64 bits: 64
    Desktop: Pantheon Distro: elementary OS 7 Horus
Machine:
  Type: Laptop System: Dell product: Latitude E7450 v: N/A
    serial: <superuser required>
  Mobo: Dell model: 0D8H72 v: A00 serial: <superuser required> UEFI: Dell
    v: A24 date: 04/11/2020
Battery:
  ID-1: BAT0 charge: 24.8 Wh (73.6%) condition: 33.7/53.3 Wh (63.2%)
CPU:
  Info: dual core model: Intel Core i5-5300U bits: 64 type: MT MCP cache:
    L2: 512 KiB
  Speed (MHz): avg: 2295 min/max: 500/2900 cores: 1: 2295 2: 2295 3: 2295
    4: 2295
Graphics:
  Device-1: Intel HD Graphics 5500 driver: i915 v: kernel
  Device-2: Sunplus Innovation Integrated_Webcam_HD type: USB
    driver: uvcvideo
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: modesetting
    unloaded: fbdev,vesa gpu: i915 resolution: 1366x768~60Hz
  OpenGL: renderer: Mesa Intel HD Graphics 5500 (BDW GT2)
    v: 4.6 Mesa 22.2.5-0ubuntu0.1~22.04.3
Audio:
  Device-1: Intel Broadwell-U Audio driver: snd_hda_intel
  Device-2: Intel Wildcat Point-LP High Definition Audio
    driver: snd_hda_intel
  Sound Server-1: ALSA v: k5.19.0-50-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Bluetooth:
  Device-1: Intel Bluetooth wireless interface type: USB driver: btusb
  Report: hciconfig ID: hci0 rfk-id: 2 state: down
    bt-service: enabled,running rfk-block: hardware: no software: no
    address: 4C:34:88:62:0A:92
Drives:
  Local Storage: total: 465.76 GiB used: 17.62 GiB (3.8%)
  ID-1: /dev/sda vendor: Seagate model: ST500LX012-1LM162-SSHD
    size: 465.76 GiB
Partition:
  ID-1: / size: 92.95 GiB used: 17.6 GiB (18.9%) fs: ext4 dev: /dev/sda8
  ID-2: /boot/efi size: 1022 MiB used: 15.5 MiB (1.5%) fs: vfat
    dev: /dev/sda6
Swap:
  ID-1: swap-1 type: partition size: 4 GiB used: 0 KiB (0.0%) dev: /dev/dm-0
Sensors:
  System Temperatures: cpu: 53.0 C mobo: 41.0 C sodimm: SODIMM C
  Fan Speeds (RPM): cpu: 0
Info:
  Processes: 263 Uptime: 31m Memory: 7.63 GiB used: 2.42 GiB (31.6%)
  Shell: fish inxi: 3.3.13
```

### PR DESCRIPTION
**Pull request by jeremypw**
Fixes #2179 
Fixes #2271 

 - [x] Fix resorting after adding/renaming a file
 - [x] Fix appearance/persistence of Code backup files if "Show Hidden Files" is "OFF"

* Added insert_sorted function to model
* Added throttled resort function to model
* Used appropriate model functions
* Fixed side effects on rename after new file creation
* Made `is_hidden` property construct-only and include files with `~` suffix.

### CODE REVIEW

**Review by zeebok — APPROVED** [review]
This looks good to me. I will give it a test but feel free to merge anyway

**Comment by zeebok** [comment]
Did some testing. I tried by editing the readme, closing, re-opening to edit, closing, etc. Usually worked but occasionally it would not sort. Not sure if a different issue is showing itself here or is related to this.

After editing README:
Screenshot from 2023-08-05 14 11 57

After closing README:
Screenshot from 2023-08-05 14 12 23

Additionally the temp files don't disappear until I refresh with `<Ctrl R>`

**Comment by jeremypw** [comment]
@zeebok Yes, I just noticed that myself.  It works if you delete a file from the terminal but for some reason not if it is a backup file deleted by Code.  Investigating....

**Comment by jeremypw** [comment]
Actually I am not sure that that issue is part of this PR since this is focused at *resorting* after adding/renaming a file.  When a file is removed, the sort order does not change.  I could probably fix the issue by resorting after deletion as well but not sure that is the most efficient way. I see whether there is a simpler way of getting the view to redraw after deletion first (it does after a terminal delete so ...)

**Comment by jeremypw** [comment]
OK, so the problem is that the backup file is a hidden file and should not be visible anyway if "show-hidden" is off (and should not be added to the model).  If "show-hidden" is on, then it gets removed as expected.

**Comment by jeremypw** [comment]
Looks like this regression was introduced by https://github.com/elementary/files/pull/2200/files :disappointed: 
Need to check for `~` as a *suffix* as well.

**Comment by jeremypw** [comment]
@zeebok I have added the fix for the issue you noticed to this PR to save time, as it is relatively small,  but should strictly be a separate PR.  Please let me know if you want it separated.

**Review by zeebok — APPROVED** [review]
Well that seems to fix the issue I was seeing of the readme temp file being properly sorted with everything else. To me that fits this PR. I can open a separate issue for not seeing the .goutputstream files disappear even though they are deleted until some kind of view refresh.

**Comment by jeremypw** [comment]
The `.goutputstream` issue was supposed to have been fixed by #2200 so that is another regression.  However, lets merge this and I'll fix that separately.

**Pull request merged**
