### PR TITLE
Fix Clang10 build

### PR DESCRIPTION
**Pull request by jeremypw**
See #1341 

The Vala compiler does not correctly handle the `return_if_fail ()` in async functions as it gets expanded within a boolean function.  With Clang10 this causes the build to fail.  Not sure what the effect would be if this were actually triggered at run time.   

Only the ctags plugin uses this macro within an async function so it is just replaced with a simple `if` clause (which compiles to correct C code).

### CODE REVIEW

**Comment by tintou** [comment]
I think that technically, if you put `GOF.File file` as an argument, Vala should throw a warning if file is NULL though

**Comment by jeremypw** [comment]
@tintou My understanding is that Vala can't tell at build time whether the file is null (possibly due to a previous program error) and wont stop the file being referenced (causing a seg fault) at run time.

I think these guards were put in as a quick fix to prevent old undiagnosed bugs causing the color tagger to crash.  They may no longer be required.

**Comment by jeremypw** [comment]
I'll ask the reporter to confirm it fixes the CLang10 issue before merging.

**Comment by jeremypw** [comment]
Reporter confirms this fixes the CLang10 issue.

**Pull request merged**
