### PR TITLE
Improve load speed

### LINKED ISSUE #1422: Every action is slow in folder with lots of folders/files.
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
In my music folder (which has 1000+ folders) every action is slow, resizing the window is slow, creating a new folder and typing the name is slow, etc.

image

### To Reproduce
1. Create folder with lots of subfolders
2. Open files to folder
3. See error by resizing window, and renaming folders. See that it is insanely slow.

### Expected behavior
No lag when resizing window, no lag when performing actions like typing in filenames.

### Screenshots or screen recordings
bug-opt

## Platform Information
image

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context
This seems to happen in terminal as well when there is lots of text in the buffer, not sure if it's related to scroll view performance or what, likely upstream widget issue, either way we should get to the bottom of it.

### LINKED ISSUE #1794: Thumbnail generation and large folder loading could be faster in general
## Problem

Thumbnail generation and large folder loading could be faster in general.

## Proposal

As of this writing, Elementary OS generates image thumbnails faster than the default file managers in other distros, but the wish is to load large folders instantaneously, or at the least, fast enough that the user does not notice the wait. This will be useful for artists and those who manage thousands of images in a folder and would rather not wait several seconds or minutes for a large folder to load, and do not want to install another file manager because Files is great!

The image thumbnailer and/or whatever loads the files could utilize multiple threads and/or the GPU. Currently, it appears that Files does most, if not all, of its processing on only one CPU thread.  Most users these days have multi-core, multi-threaded processors and powerful GPUs.

If whatever code that currently loads the files is based on ancient code/libraries, then that code could be rewritten to take advantage of modern hardware.

### LINKED ISSUE #1939: UI is unresponsive while on large folders
When on a large folder files become unresponsive on navigating, resize and maximizing.

The video below shows this behavior.

https://user-images.githubusercontent.com/51864789/145437883-38914477-1aa8-479f-a435-e4842610a52b.mp4

System: eOS 6 Odin
Kernel: Linux 5.11.0-41-generic
Ram: 8Gib
SSD 1Tb NVMe
CPU:  Core i5-8265U
No graphic card

The same doesn't happen when I use Nautilus or Dolphin on this same computer.

### LINKED ISSUE #1987: Subfolders in ListView have duplicate entries after a deletion
### What Happened?

There is this weird bug in Files app where each folder is shown twice or thrice.

elementaryOS Files App Bug

### Steps to Reproduce

1. Open a directory.
2. Delete a folder.
3. Now open another folder in tree view by pressing <kbd>→</kbd> key.

### Expected Behavior

Each sub-folder must be shown only once.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

_No response_

### Hardware Info

_No response_

### LINKED ISSUE #1996: Visual reordering when opening large folders in list mode
### What Happened?

There might be some overlap with the following issue but my symptom seems a bit different. 
- https://github.com/elementary/files/issues/1939
- https://github.com/elementary/files/issues/1794

I see Files visually rearranging files in the list or column mode. It does not seem to matter whether I sort files on name or modified. 
In general it seems to take many times longer to open folders in Files than in the file chooser. 

## List
Screen record from 2022-01-25 22 52 19 list mode

## Columns
Screen record from 2022-01-25 22 55 10 columns

## Grid
In grid mode it also takes long, but no visual re-ordering
Screen record from 2022-01-25 22 54 01 grid

## Native file chooser
Also notice how opening the same folder in the native file chooser takes no time at all
Screen record from 2022-01-25 22 59 21 file chooser

### Steps to Reproduce

1. Open Files
2. Go to a folder with lot's of files

### Expected Behavior

It takes a bit longer, but not 6 seconds while seeing files being re-arranged. 

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

_No response_

### Hardware Info

OS: elementary OS 6.1 Jólnir x86_64 
Host: XPS 15 9550 
Kernel: 5.13.0-27-generic 
Uptime: 5 hours, 9 mins 
Packages: 2099 (dpkg), 90 (flatpak) 
Shell: bash 5.0.17 
Resolution: 3840x2160, 3840x2160 
DE: Pantheon 
WM: Mutter(Gala) 
Theme: io.elementary.stylesheet.blueberry [GTK3] 
Icons: elementary [GTK3] 
Terminal: io.elementary.t 
CPU: Intel i7-6700HQ (8) @ 3.500GHz 
GPU: NVIDIA GeForce GTX 960M 
GPU: Intel HD Graphics 530 
Memory: 15949MiB / 31924MiB

### PR DESCRIPTION
**Pull request by jeremypw**
Partially fixes #1794 
Partially fixes #1422
Partially fixes #1939
Fixes #1987 
Fixes #1996

Advantage is taken of the fact that when initially loading a directory, the model is empty  and unsorted and only root level items are loaded.  A new simpler, faster method for adding all the files in the directory (filtered according to hidden file setting) in one operation is introduced and similar methods for loading subdirectories.

Also, rather than emitting and processing a signal for every file as it is loaded into the Directory object, a single signal is emitted once all the files have been loaded.

Further improvement is made by not fully updating the file from the info until the file is actually displayed.  When initially loaded we only need to set the properties needed by the model sorting/filtering.

This greatly reduces the time taken to initially construct the model (more than a factor of 10).  The main delay becomes laying out the IconView.

This will not fix issues related to large modifications of a loaded directory, those will be addressed in a future PR.

### CODE REVIEW

**Comment by jeremypw** [comment]
Example for 20000 (small) files:
**This PR**
TIme to emit "done-loaded" signal approx 1.5 seconds
Show ListView (total, approx):  <2 seconds
Show IconView (total, approx): 20 seconds

**Master**
TIme to emit "done-loaded" signal approx 192 seconds
Show ListView (total, approx) 194 seconds
Show IconView (total, approx) 224 seconds

This shows there has been a regression in the time taken to load the Directory object and construct the model such that for large folders it dominates the total time taken to show the view.

In this PR the loading and construction of the model is approaching 100x faster and for IconView the laying out of the View dominates.

**Comment by peteruithoven** [comment]
Difference is night and day, an incredible improvement. 

You probably already noticed but the directory icons are initially document like icons? 
Screen record from 2022-01-29 16 15 24
Screen record from 2022-01-29 16 13 21

**Comment by jeremypw** [comment]
@peteruithoven Thanks for the comment! Yes, I need to find some time to work on regressions.

**Comment by jeremypw** [comment]
Closing as too old.  May incorporate ideas into Gtk4 version.

**Pull request closed without merging**
